name: doctor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  flutter_easyloading: ^3.0.5
  url_launcher: ^6.1.12
  amap_flutter_map: ^3.0.0
  get: 4.6.5
  dio: ^5.3.2
  intl: ^0.18.1
  pull_to_refresh: ^2.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

